MAIN:
  SPLIT: 'train'

NAVI:
  GT_OCC_MAP_TYPE: 'NAV_MESH'
  HFOV: 360
  PERCEPTION: Potential
  STRATEGY: Greedy
  D_type: 'Skeleton'

PRED:
  PARTIAL_MAP:
    BATCH_SIZE: 64
    CHECKNAME: unet
    DEVICE: cuda
    DIVIDE_AREA: 100
    EPOCHS: 6
    EVAL_INTERVAL: 1
    FLAG_VISUALIZE_PRED_LABELS: False
    INPUT: occ_and_sem
    INPUT_CHANNEL: 45 # 42 + 3
    OUTPUT_CHANNEL: 4
    INPUT_WH: (480, 480)
    LOSS_TYPE: L1
    NEIGHBOR_SIZE: 40
    NUM_GENERATED_SAMPLES_PER_SCENE: 5000
    NUM_WORKERS: 24
    RESUME: ''
    SAVED_FOLDER: 'output/model_weights_UNet_input_partial_map'
    STEP_GAP: 5
    LR: 1e-3
    NUM_PROCESS: 24
    multiprocessing: 'mp'
    GEN_SAMPLES_SAVED_FOLDER: 'output/training_data_input_partial_map_5000samples'


SAVE:
  TESTING_RESULTS_FOLDER: ''

SEM_MAP:
  CELL_SIZE: 0.05
  GRID_CLASS_SIZE: 42